import json

products = [
  # 1. Cellulose Ethers & Polymers (7 items)
  {
    "id": "hpmc",
    "name": { "en": "Hydroxypropyl Methyl Cellulose (HPMC)", "ar": "هيدروكسي بروبيل ميثيل السليلوز (HPMC)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "9004-65-3",
    "formula": "Non-ionic Cellulose Ether",
    "appearance": { "en": "White powder, readily soluble in cold or hot water, pseudo-plastic viscosity", "ar": "بودرة بيضاء ناصعة، سريعة الذوبان في الماء البارد والساخن مع لزوجة كاذبة المرونة" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية متعددة الطبقات سعة 25 كجم" },
    "applications": { "en": ["Water-based paints", "Detergents", "Wall putty", "Adhesive putty & tile adhesives", "Marble repair"], "ar": ["الدهانات المائية", "المنظفات", "معجون الحوائط", "غراء البلاط والرخام", "الخلطات الإسمنتية الثقيلة"] },
    "imageUrl": "/images/catalog/hpmc.svg",
    "featured": True
  },
  {
    "id": "hec",
    "name": { "en": "Hydroxyethyl Cellulose (HEC)", "ar": "هيدروكسي إيثيل السليلوز (HEC)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "9004-62-0",
    "formula": "Cellulose 2-hydroxyethyl ether",
    "appearance": { "en": "White free-flowing powder", "ar": "بودرة بيضاء ناعمة حرة التدفق" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية متعددة الطبقات سعة 25 كجم" },
    "applications": { "en": ["Water system emulsion paints", "Detergents", "Wall paste", "Heavy mixtures"], "ar": ["دهانات الأنظمة المائية", "المنظفات", "معجون الجدران", "الخلطات الثقيلة"] },
    "imageUrl": "/images/catalog/hec.svg",
    "featured": False
  },
  {
    "id": "mhec",
    "name": { "en": "Methyl Hydroxyethyl Cellulose (MHEC)", "ar": "ميثيل هيدروكسي إيثيل السليلوز (MHEC)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "9032-42-2",
    "formula": "Modified Cellulose Ether",
    "appearance": { "en": "White powder with excellent water retention", "ar": "بودرة بيضاء تمتاز بقدرة فائقة على الاحتفاظ بالماء ومقاومة الانزلاق" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية متعددة الطبقات سعة 25 كجم" },
    "applications": { "en": ["Tile adhesives", "Cementitious renders", "Plasters & putties"], "ar": ["لواصق السيراميك والبلاط", "اللياسة الجافة", "معاجين التشطيب"] },
    "imageUrl": "/images/catalog/mhec.svg",
    "featured": False
  },
  {
    "id": "hemc",
    "name": { "en": "Hydroxyethyl Methyl Cellulose (HEMC)", "ar": "هيدروكسي إيثيل ميثيل السليلوز (HEMC)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "9032-42-2",
    "formula": "Cellulose Methyl Hydroxyethyl Ether",
    "appearance": { "en": "White fine powder, thermal stability", "ar": "بودرة بيضاء دقيقة ذات ثبات حراري ممتاز" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية متعددة الطبقات سعة 25 كجم" },
    "applications": { "en": ["High-temperature dry mortars", "Exterior wall putty", "Water-based paints"], "ar": ["الملاط الجاف للأجواء الحارة", "معجون الواجهات الخارجية", "الدهانات المائية"] },
    "imageUrl": "/images/catalog/hemc.svg",
    "featured": False
  },
  {
    "id": "rdp",
    "name": { "en": "Dispersible Polymer Powder (RDP)", "ar": "بودرة البوليمر القابلة لإعادة التشتت (RDP)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "24937-78-8",
    "formula": "Copolymer of Vinyl Acetate",
    "appearance": { "en": "White free-flowing powder", "ar": "بودرة بيضاء حرة التدفق قابلة لإعادة التشتت في الماء" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية متعددة الطبقات سعة 25 كجم" },
    "applications": { "en": ["Elastic cement paint repair material", "Flexible wall putty (mix dry putty)", "Ceramic tile adhesive", "Break the marble"], "ar": ["مواد إصلاح الإسمنت المرنة", "معجون الحوائط المرن", "لواصق السيراميك والبلاط", "معالجة ولحام الرخام"] },
    "imageUrl": "/images/catalog/rdp.svg",
    "featured": True
  },
  {
    "id": "organo-bentonite",
    "name": { "en": "ORGANO BENTONITE Clay Solvent Base", "ar": "أورجانو بنتونايت (أساس مذيب)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "68953-58-2",
    "formula": "Organophilic Montmorillonite",
    "appearance": { "en": "White fine powder, rheological thixotropic agent (Grades 34, 38, 27, SD1, SD2, SD3)", "ar": "بودرة بيضاء ناعمة، مضاف ريولوجي ومضاد للترسيب (درجات: 34، 38، 27، SD1, SD2, SD3)" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية متعددة الطبقات سعة 25 كجم" },
    "applications": { "en": ["Wood paint", "Adhesives", "Anti-corrosion paint", "Lubricating grease", "Industry paint", "Marine paint"], "ar": ["دهانات الأخشاب", "المواد اللاصقة", "الدهانات المقاومة للصدأ", "شحوم التزييت", "الدهانات الصناعية والبحرية"] },
    "imageUrl": "/images/catalog/organo-bentonite.svg",
    "featured": True
  },
  {
    "id": "styrene-acrylic-polymer",
    "name": { "en": "Styrene Acrylic Emulsion (Co-Polymer / Homo-Polymer)", "ar": "بوليمر ستيرين أكريليك (كوبوليمر / هوموبوليمر)" },
    "category": "cellulose-thickeners-polymers",
    "casNumber": "25085-34-1",
    "formula": "(C8H8.C4H6O2)x",
    "appearance": { "en": "Milky white aqueous polymer binder", "ar": "مستحلب بوليمري مائي بلون أبيض حليبي" },
    "packaging": { "en": "200 Kg industrial drums / 1000L IBC", "ar": "براميل 200 كجم / حاويات IBC" },
    "applications": { "en": ["Interior & exterior emulsion paints", "Textile coatings", "Cement bonding agents"], "ar": ["الدهانات المائية الداخلية والخارجية", "روابط المنسوجات", "روابط الخرسانة والإسمنت"] },
    "imageUrl": "/images/catalog/styrene-acrylic-polymer.svg",
    "featured": False
  },

  # 2. Driers & Specialty Additives (12 items)
  {
    "id": "cobalt-octoate-10",
    "name": { "en": "Cobalt Octoate 10%", "ar": "أوكتوات الكوبالت 10%" },
    "category": "paint-driers-additives",
    "casNumber": "136-52-7",
    "formula": "Co(C8H15O2)2",
    "appearance": { "en": "Deep violet-blue liquid, active primary surface drier", "ar": "سائل أزرق بنفسجي داكن، المجفف السطحي الأساسي والأكثر كفاءة" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Alkyd resin paints", "Varnishes", "Printing inks", "Polyester resin cure accelerator"], "ar": ["دهانات الراتنجات الألكيدية", "الورنيشات الشفافة", "أحبار الطباعة", "مسرع تصليب راتنجات البوليستر"] },
    "imageUrl": "/images/catalog/cobalt-octoate-10.svg",
    "featured": True
  },
  {
    "id": "calcium-octoate-10",
    "name": { "en": "Calcium Octoate 10%", "ar": "أوكتوات الكالسيوم 10%" },
    "category": "paint-driers-additives",
    "casNumber": "6107-56-8",
    "formula": "Ca(C8H15O2)2",
    "appearance": { "en": "Clear yellowish liquid, auxiliary through-drier and pigment wetting agent", "ar": "سائل رائق مائل للصفرة، مجفف عميق وعامل ترطيب ومساعد لتشتيت الصبغات" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Enamels", "Architectural paints", "Loss-of-dry inhibitor"], "ar": ["دهانات الزيت والإنامل", "الدهانات المعمارية", "منع فقدان سرعة الجفاف أثناء التخزين"] },
    "imageUrl": "/images/catalog/calcium-octoate-10.svg",
    "featured": False
  },
  {
    "id": "zirconium-octoate-18",
    "name": { "en": "Zirconium Octoate 18%", "ar": "أوكتوات الزركونيوم 18%" },
    "category": "paint-driers-additives",
    "casNumber": "22464-99-9",
    "formula": "Zr(C8H15O2)4",
    "appearance": { "en": "Clear light straw liquid, premier eco-friendly through-drier", "ar": "سائل شفاف، بديل بيئي فائق الفعالية لمجففات الرصاص لضمان الجفاف العميق" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Lead-free industrial coatings", "Automotive finishes", "Marine paints"], "ar": ["الطلاءات الخالية من الرصاص", "دهانات السيارات", "الدهانات البحرية"] },
    "imageUrl": "/images/catalog/zirconium-octoate-18.svg",
    "featured": False
  },
  {
    "id": "zinc-octoate",
    "name": { "en": "Zinc Octoate", "ar": "أوكتوات الزنك" },
    "category": "paint-driers-additives",
    "casNumber": "136-53-8",
    "formula": "Zn(C8H15O2)2",
    "appearance": { "en": "Clear liquid, auxiliary drier, prevents wrinkling and improves hardness", "ar": "سائل شفاف، يمنع تجعد فيلم الطلاء ويزيد من الصلابة واللمعان" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Baking finishes", "Anti-wrinkling formulations", "Clear wood varnishes"], "ar": ["دهانات الأفران الحرارية", "تركيبات مقاومة التجعد", "ورنيش الأخشاب"] },
    "imageUrl": "/images/catalog/zinc-octoate.svg",
    "featured": False
  },
  {
    "id": "lead-octoate-36",
    "name": { "en": "Lead Octoate 36%", "ar": "أوكتوات الرصاص 36%" },
    "category": "paint-driers-additives",
    "casNumber": "73018-26-5",
    "formula": "Pb(C8H15O2)2",
    "appearance": { "en": "Amber clear heavy through-drier liquid", "ar": "سائل عنبري شفاف، مجفف كلاسيكي عالي التركيز للجفاف العميق" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Heavy industrial maintenance paints", "Steel infrastructure coatings"], "ar": ["دهانات الصيانة الصناعية الثقيلة", "طلاء المنشآت المعدنية والجسور"] },
    "imageUrl": "/images/catalog/lead-octoate-36.svg",
    "featured": False
  },
  {
    "id": "iron-octoate",
    "name": { "en": "Iron Octoate", "ar": "أوكتوات الحديد" },
    "category": "paint-driers-additives",
    "casNumber": "19583-54-1",
    "formula": "Fe(C8H15O2)3",
    "appearance": { "en": "Dark reddish-brown liquid", "ar": "سائل بني مائل للاحمرار، مجفف للدهانات الداكنة" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["High-temperature baking finishes", "Dark colored industrial enamels"], "ar": ["دهانات الحرق الحراري عالي الحرارة", "الإنامل الصناعي ذو الألوان الداكنة"] },
    "imageUrl": "/images/catalog/iron-octoate.svg",
    "featured": False
  },
  {
    "id": "copper-octoate",
    "name": { "en": "Copper Octoate", "ar": "أوكتوات النحاس" },
    "category": "paint-driers-additives",
    "casNumber": "20543-04-8",
    "formula": "Cu(C8H15O2)2",
    "appearance": { "en": "Dark green viscous liquid", "ar": "سائل لزج بلون أخضر داكن ذو خواص مبيدة للفطريات" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Wood preservation", "Antifouling marine coatings", "Textile rot-proofing"], "ar": ["حماية ومعالجة الأخشاب", "الدهانات البحرية المانعة لالتصاق العوالق", "حماية الأقمشة والخيام"] },
    "imageUrl": "/images/catalog/copper-octoate.svg",
    "featured": False
  },
  {
    "id": "barium-octoate",
    "name": { "en": "Barium Octoate", "ar": "أوكتوات الباريوم" },
    "category": "paint-driers-additives",
    "casNumber": "2457-01-4",
    "formula": "Ba(C8H15O2)2",
    "appearance": { "en": "Light yellow clear liquid", "ar": "سائل أصفر فاتح شفاف" },
    "packaging": { "en": "200 Kg steel drums", "ar": "براميل حديدية 200 كجم" },
    "applications": { "en": ["Loss-of-dry prevention", "Gloss retention in alkyds", "PVC heat stabilizers"], "ar": ["منع تراجع سرعة الجفاف", "الحفاظ على لمعان الدهان", "مثبتات حرارية للبلاستيك"] },
    "imageUrl": "/images/catalog/barium-octoate.svg",
    "featured": False
  },
  {
    "id": "anti-skin-meko",
    "name": { "en": "Anti-skin MEKO (Methyl Ethyl Ketoxime)", "ar": "مضاد تكوّن القشرة ميكو (MEKO)" },
    "category": "paint-driers-additives",
    "casNumber": "96-29-7",
    "formula": "C4H9NO",
    "appearance": { "en": "Clear volatile organic liquid anti-skinning agent", "ar": "سائل شفاف متطاير لمنع تكوّن القشرة السطحية في علب الدهان" },
    "packaging": { "en": "200 Kg steel drums / 30 Kg cans", "ar": "براميل 200 كجم / جوالين 30 كجم" },
    "applications": { "en": ["Alkyd paints anti-skinning", "Solvent for lacquers and resins", "Scale inhibitor"], "ar": ["منع تجلط وتشكل القشرة في دهانات الألكيد والورنيش", "مذيب سريع ومثبط ترسبات"] },
    "imageUrl": "/images/catalog/anti-skin-meko.svg",
    "featured": True
  },
  {
    "id": "biocide-isothiazolinone",
    "name": { "en": "Isothiazolinonas (Biocide)", "ar": "مبيد بيولوجي ومادة حافظة (آيزوثيازولينون)" },
    "category": "paint-driers-additives",
    "casNumber": "55965-84-9",
    "formula": "CMIT/MIT Complex",
    "appearance": { "en": "Clear amber liquid in-can preservative", "ar": "سائل عنبري شفاف، مبيد بكتيري وحافظ داخل العلبة واسع الطيف" },
    "packaging": { "en": "200 Kg drums / 30 Kg gallons", "ar": "براميل 200 كجم / جوالين 30 كجم" },
    "applications": { "en": ["Polymer dispersions", "Latex paints & stucco", "Rheology modifiers & adhesives", "Pigment pastes"], "ar": ["مستحلبات البوليمر واللاتكس", "دهانات البلاستيك والمعجون والستوكو", "المعدلات الريولوجية والمواد اللاصقة", "معاجين التلوين"] },
    "imageUrl": "/images/catalog/biocide-isothiazolinone.svg",
    "featured": True
  },
  {
    "id": "anti-foams",
    "name": { "en": "Anti-Foams (Mineral Oil Based, Silicone-Free)", "ar": "مضاد رغوة عالي الفعالية (خالٍ من السيليكون)" },
    "category": "paint-driers-additives",
    "casNumber": "64742-52-5",
    "formula": "Hydrocarbon Defoamer",
    "appearance": { "en": "Opaque yellowish liquid defoamer", "ar": "سائل معتم، مزيل ومثبط للرغوة عالي الفعالية على أساس زيوت معدنية خالية من السيليكون" },
    "packaging": { "en": "200 Kg drums / 25 Kg cans", "ar": "براميل 200 كجم / جوالين 25 كجم" },
    "applications": { "en": ["Emulsion paints & plaster", "Plastic coatings", "Printing inks & fermentation"], "ar": ["دهانات المستحلبات واللياسة", "الطلاءات البلاستيكية", "أحبار الطباعة وعمليات التخمر"] },
    "imageUrl": "/images/catalog/anti-foams.svg",
    "featured": False
  },
  {
    "id": "dispersing-agent",
    "name": { "en": "Dispersing Agent (Sodium & Ammonium Polyacrylate)", "ar": "مشتت أصباغ مائي (بولي أكريلات الصوديوم والأمونيوم)" },
    "category": "paint-driers-additives",
    "casNumber": "9003-04-7",
    "formula": "Polyacrylic Acid Salts",
    "appearance": { "en": "Clear to yellowish liquid", "ar": "سائل رائق مائل للصفرة لتشتيت الصبغات والمواد المالئة" },
    "packaging": { "en": "200 Kg drums / 25 Kg cans", "ar": "براميل 200 كجم / جوالين 25 كجم" },
    "applications": { "en": ["Paints water based and coating systems", "Slurries and mineral dispersions"], "ar": ["الدهانات المائية وأنظمة الطلاء", "تشتيت المواد المالئة والصبغات في الماء"] },
    "imageUrl": "/images/catalog/dispersing-agent.svg",
    "featured": False
  },

  # 3. Fillers, Pigments & Resins (11 items)
  {
    "id": "zinc-dust",
    "name": { "en": "Zinc Dust (High Purity Zinc Powder)", "ar": "بودرة غبار الزنك (عالية النقاوة)" },
    "category": "fillers-pigments-resins",
    "casNumber": "7440-66-6",
    "formula": "Zn",
    "appearance": { "en": "Fine metallic grey powder", "ar": "بودرة رمادية معدنية دقيقة عالية النقاوة" },
    "packaging": { "en": "25 Kg / 50 Kg steel drums & bags", "ar": "براميل حديدية وأكياس 25 كجم / 50 كجم" },
    "applications": { "en": ["Zinc-rich anti-corrosion epoxy primers", "Protective marine coatings", "Chemical synthesis"], "ar": ["برايمرات الإيبوكسي الغنية بالزنك لمقاومة الصدأ", "الدهانات البحرية والصناعية الواقية", "الصناعات الكيميائية"] },
    "imageUrl": "/images/catalog/zinc-dust.svg",
    "featured": False
  },
  {
    "id": "zinc-phosphate",
    "name": { "en": "Zinc Phosphate", "ar": "فوسفات الزنك (صبغة مانعة للصدأ)" },
    "category": "fillers-pigments-resins",
    "casNumber": "7779-90-0",
    "formula": "Zn3(PO4)2.2H2O",
    "appearance": { "en": "Non-toxic white anti-corrosive powder", "ar": "بودرة بيضاء غير سامة مانعة للتآكل والصدأ" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية 25 كجم" },
    "applications": { "en": ["Anti-corrosion primers", "Coil coatings", "Alkyd and epoxy metal protection"], "ar": ["دهانات التأسيس المانعة للصدأ", "طلاء اللفائف المعدنية", "حماية المعادن بالأنظمة الألكيدية والإيبوكسي"] },
    "imageUrl": "/images/catalog/zinc-phosphate.svg",
    "featured": False
  },
  {
    "id": "zinc-stearate",
    "name": { "en": "Zinc Stearate", "ar": "ستيرات الزنك الصناعية" },
    "category": "fillers-pigments-resins",
    "casNumber": "557-05-1",
    "formula": "Zn(C18H35O2)2",
    "appearance": { "en": "Ultra-fine silky white hydrophobic powder", "ar": "بودرة بيضاء حريرية ناعمة طاردة للماء" },
    "packaging": { "en": "20 Kg multi-layer bags", "ar": "أكياس 20 كجم" },
    "applications": { "en": ["Wood coating sanding sealers", "Plastic masterbatch lubricant", "Rubber release agent"], "ar": ["سيلر الأخشاب ومساعد الصنفرة", "مزلّق لصناعات البلاستيك والماسترباتش", "عامل فك قوالب المطاط"] },
    "imageUrl": "/images/catalog/zinc-stearate.svg",
    "featured": False
  },
  {
    "id": "fumed-silica",
    "name": { "en": "Fumed Silica", "ar": "فيومد سيليكا (معدل اللزوجة والتثخن)" },
    "category": "fillers-pigments-resins",
    "casNumber": "112945-52-5",
    "formula": "SiO2",
    "appearance": { "en": "Extremely light fluffy white powder", "ar": "بودرة بيضاء هشة وخفيفة جداً تمنح انسيابية ومقاومة للترسيب" },
    "packaging": { "en": "10 Kg multi-layer kraft bags", "ar": "أكياس ورقية خاصة سعة 10 كجم" },
    "applications": { "en": ["Thixotropy and rheology control in paints", "Adhesives & sealants anti-sagging", "Silicones"], "ar": ["التحكم بالريولوجيا ومقاومة السيلان في الدهانات", "المواد اللاصقة والسيليكون والمعاجين"] },
    "imageUrl": "/images/catalog/fumed-silica.svg",
    "featured": True
  },
  {
    "id": "carbon-black",
    "name": { "en": "Carbon Black", "ar": "أسود الكربون (صبغة كربونية عالية السواد)" },
    "category": "fillers-pigments-resins",
    "casNumber": "1333-86-4",
    "formula": "C",
    "appearance": { "en": "High jetness deep black powder", "ar": "بودرة سوداء فاحمة ذات قوة تلوين وتغطية جبارة" },
    "packaging": { "en": "25 Kg bags", "ar": "أكياس 25 كجم" },
    "applications": { "en": ["Paints & industrial coatings", "Printing inks", "Plastics and rubber reinforcing"], "ar": ["الدهانات والطلاءات الصناعية", "أحبار الطباعة", "صناعة البلاستيك وتقوية المطاط"] },
    "imageUrl": "/images/catalog/carbon-black.svg",
    "featured": False
  },
  {
    "id": "maleic-resin",
    "name": { "en": "Maleic Resin", "ar": "راتنج المالييك (Maleic Rosin Resin)" },
    "category": "fillers-pigments-resins",
    "casNumber": "94581-16-5",
    "formula": "Maleic Modified Rosin",
    "appearance": { "en": "Light yellow transparent solid flakes / granules", "ar": "حبيبات وقشور صلبة شفافة صفراء فاتحة" },
    "packaging": { "en": "25 Kg bags", "ar": "أكياس 25 كجم" },
    "applications": { "en": ["Gravure inks", "Nitrocellulose wood lacquers", "Road marking paints"], "ar": ["أحبار الروتوجرافور والطباعة", "ورنيش النيتروسليلوز للأخشاب", "دهانات تخطيط الطرق"] },
    "imageUrl": "/images/catalog/maleic-resin.svg",
    "featured": False
  },
  {
    "id": "natural-barium-sulphate",
    "name": { "en": "Natural Barium Sulphate (Barite)", "ar": "كبريتات الباريوم الطبيعية (بارايت)" },
    "category": "fillers-pigments-resins",
    "casNumber": "7727-43-7",
    "formula": "BaSO4",
    "appearance": { "en": "Heavy inert white mineral powder", "ar": "بودرة معدنية بيضاء ثقيلة خاملة كيميائياً" },
    "packaging": { "en": "25 Kg / 50 Kg bags", "ar": "أكياس 25 كجم / 50 كجم" },
    "applications": { "en": ["Industrial coatings", "Anti-acid chemical resistant paints", "Friction materials & plastics"], "ar": ["الدهانات الصناعية الثقيلة", "الدهانات المقاومة للأحماض والمواد الكيميائية", "البلاستيك وتيل المكابح"] },
    "imageUrl": "/images/catalog/natural-barium-sulphate.svg",
    "featured": False
  },
  {
    "id": "lithopone",
    "name": { "en": "Lithopone (ZnS + BaSO4)", "ar": "الليثوبون (صبغة بيضاء)" },
    "category": "fillers-pigments-resins",
    "casNumber": "1345-05-7",
    "formula": "ZnS.BaSO4",
    "appearance": { "en": "White fine mineral pigment powder", "ar": "بودرة بيضاء دقيقة، صبغة اقتصادية ذات عتامة ممتازة" },
    "packaging": { "en": "25 Kg bags", "ar": "أكياس 25 كجم" },
    "applications": { "en": ["Water-based interior paints", "Rubbers and masterbatches", "Paper coating"], "ar": ["الدهانات المائية الداخلية", "صناعة المطاط والماسترباتش", "طلاء وتبييض الورق"] },
    "imageUrl": "/images/catalog/lithopone.svg",
    "featured": False
  },
  {
    "id": "mica",
    "name": { "en": "Mica Powder (Maica)", "ar": "بودرة المايكا المعدنية" },
    "category": "fillers-pigments-resins",
    "casNumber": "12001-26-2",
    "formula": "Potassium Aluminum Silicate",
    "appearance": { "en": "Lamellar off-white platy powder", "ar": "بودرة صفائحية تعزل الرطوبة وتعزز المتانة الميكانيكية" },
    "packaging": { "en": "25 Kg bags", "ar": "أكياس 25 كجم" },
    "applications": { "en": ["Barrier anti-corrosive coatings", "Heat resistant paints", "Joint fillers"], "ar": ["الدهانات الحاجزة المانعة للصدأ والماء", "الدهانات المقاومة للحرارة", "معاجين الفواصل والجبس"] },
    "imageUrl": "/images/catalog/mica.svg",
    "featured": False
  },
  {
    "id": "talc",
    "name": { "en": "Industrial Talc Powder", "ar": "بودرة التلك الصناعية" },
    "category": "fillers-pigments-resins",
    "casNumber": "14807-96-6",
    "formula": "Mg3Si4O10(OH)2",
    "appearance": { "en": "Soft white lamellar mineral powder", "ar": "بودرة بيضاء ناعمة ملساء ممتازة للصنفرة وتعديل اللمعان" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية 25 كجم" },
    "applications": { "en": ["Automotive body putties", "Paints & primers", "Plastics and ceramics"], "ar": ["معاجين السيارات والأسطح", "الدهانات التأسيسية لتسهيل الصنفرة", "صناعات البلاستيك والخزف"] },
    "imageUrl": "/images/catalog/talc.svg",
    "featured": False
  },
  {
    "id": "pcc",
    "name": { "en": "Precipitated Calcium Carbonate (PCC)", "ar": "كربونات الكالسيوم المرسبة (PCC)" },
    "category": "fillers-pigments-resins",
    "casNumber": "471-34-1",
    "formula": "CaCO3",
    "appearance": { "en": "Ultra-fine bright white powder", "ar": "بودرة بيضاء ناصعة وفائقة النعومة والنقاء الكيميائي" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية 25 كجم" },
    "applications": { "en": ["High-grade architectural paints", "Sealants & PVC profiles", "Paper & printing inks"], "ar": ["الدهانات المعمارية الفاخرة لزيادة البياض والتغطية", "معاجين البناء والسيليكون", "الورق وأحبار الطباعة"] },
    "imageUrl": "/images/catalog/pcc.svg",
    "featured": False
  },

  # 4. Industrial Solvents (7 items)
  {
    "id": "ipa-isopropanol",
    "name": { "en": "Isopropyl Alcohol (IPA)", "ar": "كحول الآيزوبروبيل (IPA)" },
    "category": "industrial-solvents",
    "casNumber": "67-63-0",
    "formula": "C3H8O",
    "appearance": { "en": "Clear colorless fast-evaporating liquid", "ar": "سائل كحولي رائق عديم اللون سريع التطاير ذو قدرة إذابة عالية" },
    "packaging": { "en": "160 Kg drums / bulk tankers", "ar": "براميل 160 كجم / صهاريج" },
    "applications": { "en": ["Flexographic printing inks", "Industrial cleaning & electronics", "Sanitizers and coatings"], "ar": ["أحبار الطباعة والفلكسو", "التنظيف وإزالة الشحوم في الإلكترونيات", "المطهرات والمذيبات الصناعية"] },
    "imageUrl": "/images/catalog/ipa-isopropanol.svg",
    "featured": True
  },
  {
    "id": "xylene",
    "name": { "en": "Xylene (Mixed Xylenes)", "ar": "الزايلين الصناعي (Xylene)" },
    "category": "industrial-solvents",
    "casNumber": "1330-20-7",
    "formula": "C8H10",
    "appearance": { "en": "Clear aromatic hydrocarbon solvent", "ar": "مذيب هيدروكربوني أروماتي نقي عديم اللون" },
    "packaging": { "en": "180 Kg drums", "ar": "براميل 180 كجم" },
    "applications": { "en": ["Alkyd, epoxy and polyurethane paint thinning", "Synthetic resins production", "Industrial cleaning"], "ar": ["تخفيف دهانات الألكيد والإيبوكسي والبولي يوريثان", "إنتاج الراتنجات التخليقية", "الثنر الصناعي عالي الجودة"] },
    "imageUrl": "/images/catalog/xylene.svg",
    "featured": True
  },
  {
    "id": "butyl-acetate",
    "name": { "en": "Butyl Acetate", "ar": "بيوتيل أسيتات (Butyl Acetate)" },
    "category": "industrial-solvents",
    "casNumber": "123-86-4",
    "formula": "C6H12O2",
    "appearance": { "en": "Clear liquid with pleasant fruity odor, medium volatility", "ar": "سائل شفاف برائحة فاكهية، متوسط التطاير ذو قوة إذابة استثنائية" },
    "packaging": { "en": "180 Kg drums", "ar": "براميل 180 كجم" },
    "applications": { "en": ["Automotive lacquers and refinish paints", "Polyurethane and nitrocellulose wood coatings", "Leather finishes"], "ar": ["دهانات السيارات واللاكيهات", "ورنيش البولي يوريثان والنيتروسليلوز للأثاث", "صناعات الجلود والمواد اللاصقة"] },
    "imageUrl": "/images/catalog/butyl-acetate.svg",
    "featured": False
  },
  {
    "id": "ethanol",
    "name": { "en": "Industrial Ethanol (Ethyl Alcohol)", "ar": "الإيثانول الصناعي (كحول الإيثيل)" },
    "category": "industrial-solvents",
    "casNumber": "64-17-5",
    "formula": "C2H5OH",
    "appearance": { "en": "Clear pure alcohol solvent", "ar": "سائل كحولي رائق شفاف متعدد الاستخدامات" },
    "packaging": { "en": "160 Kg drums", "ar": "براميل 160 كجم" },
    "applications": { "en": ["Printing inks", "Industrial cleaning", "Sanitizers & personal care"], "ar": ["أحبار الطباعة والتغليف", "التنظيف الصناعي", "المطهرات والمستحضرات"] },
    "imageUrl": "/images/catalog/ethanol.svg",
    "featured": False
  },
  {
    "id": "methanol",
    "name": { "en": "Methanol (Methyl Alcohol)", "ar": "الميثانول (كحول الميثيل)" },
    "category": "industrial-solvents",
    "casNumber": "67-56-1",
    "formula": "CH3OH",
    "appearance": { "en": "Clear volatile chemical raw material and solvent", "ar": "سائل كيميائي رائق سريع التطاير ومادة وسيطة للصناعات التخليقية" },
    "packaging": { "en": "165 Kg drums", "ar": "براميل 165 كجم" },
    "applications": { "en": ["Formaldehyde synthesis", "Biodiesel production", "Wastewater treatment denitrification"], "ar": ["تصنيع الفورمالدهيد والراتنجات", "إنتاج وقود الديزل الحيوي", "معالجة مياه الصرف والمذيبات المتخصصة"] },
    "imageUrl": "/images/catalog/methanol.svg",
    "featured": False
  },
  {
    "id": "ethyl-acetate",
    "name": { "en": "Ethyl Acetate", "ar": "إيثيل أسيتات (Ethyl Acetate)" },
    "category": "industrial-solvents",
    "casNumber": "141-78-6",
    "formula": "C4H8O2",
    "appearance": { "en": "Fast evaporating clear fruity solvent", "ar": "مذيب إستر رائق وسريع التطاير ذو رائحة مميزة" },
    "packaging": { "en": "180 Kg drums", "ar": "براميل 180 كجم" },
    "applications": { "en": ["Rotogravure & flexographic printing packaging inks", "Adhesives formulations", "Paints and varnishes"], "ar": ["أحبار طباعة التغليف المرن الروتوجرافور", "صناعة المواد اللاصقة والغراء", "الدهانات وسريعة الجفاف"] },
    "imageUrl": "/images/catalog/ethyl-acetate.svg",
    "featured": False
  },
  {
    "id": "white-spirit",
    "name": { "en": "White Spirit (Mineral Turpentine)", "ar": "الوايت سبيريت (White Spirit)" },
    "category": "industrial-solvents",
    "casNumber": "64742-82-1",
    "formula": "Petroleum Distillate",
    "appearance": { "en": "Clear petroleum solvent", "ar": "مذيب بترولي رائق ومخفف أساسي للدهانات الزيتية" },
    "packaging": { "en": "150 Kg drums", "ar": "براميل 150 كجم" },
    "applications": { "en": ["Alkyd architectural paints thinning", "Wood varnishes and stains", "Industrial degreasing and cleaning"], "ar": ["تخفيف دهانات الألكيد والورنيشات", "صبغات ودهانات الأخشاب", "إزالة الشحوم وتنظيف المعدات"] },
    "imageUrl": "/images/catalog/white-spirit.svg",
    "featured": False
  },

  # 5. Detergent Raw Materials & Surfactants (10 items)
  {
    "id": "sles-texapon",
    "name": { "en": "Sodium Lauryl Ether Sulphate (SLES 70% Texapon)", "ar": "تكسابون - كبريتات لوريل إيثر الصوديوم (SLES 70%)" },
    "category": "detergent-raw-materials",
    "casNumber": "68585-34-2",
    "formula": "C12H25O(CH2CH2O)2SO3Na",
    "appearance": { "en": "Translucent viscous aqueous paste", "ar": "معجون هلامي شفاف مائل للصفرة ذو رغوة كثيفة" },
    "packaging": { "en": "170 Kg / 220 Kg plastic drums", "ar": "براميل بلاستيكية 170 كجم / 220 كجم" },
    "applications": { "en": ["Dishwashing liquids", "Shampoos and shower gels", "Liquid laundry detergents"], "ar": ["سوائل جلي الصحون", "شامبوهات الشعر والصابون السائل", "منظفات الملابس السائلة"] },
    "imageUrl": "/images/catalog/sles-texapon.svg",
    "featured": True
  },
  {
    "id": "labsa-sulfonic",
    "name": { "en": "Linear Alkylbenzene Sulphonic Acid (LABSA 96%)", "ar": "حمض السلفونيك الخطي (LABSA 96%)" },
    "category": "detergent-raw-materials",
    "casNumber": "27176-87-0",
    "formula": "C18H30O3S",
    "appearance": { "en": "Brown viscous liquid surfactant", "ar": "سائل بني لزج عالي التركيز، المادة الأساسية الأولى في صناعة المنظفات" },
    "packaging": { "en": "215 Kg plastic drums / IBC", "ar": "براميل بلاستيكية 215 كجم / حاويات IBC" },
    "applications": { "en": ["Washing powder manufacturing", "Heavy duty liquid detergents", "Industrial degreasers"], "ar": ["تصنيع مساحيق الغسيل البودرة", "منظفات الملابس والصحون السائلة", "مزيلات الشحوم الصناعية"] },
    "imageUrl": "/images/catalog/labsa-sulfonic.svg",
    "featured": True
  },
  {
    "id": "cdea-comperlan",
    "name": { "en": "Cocodiethanolamide (CDEA / Comperlan)", "ar": "كوكو داي إيثانول أميد (CDEA - كمبرلان)" },
    "category": "detergent-raw-materials",
    "casNumber": "68603-42-9",
    "formula": "C11H23CON(CH2CH2OH)2",
    "appearance": { "en": "Viscous light amber liquid, foam booster and viscosity builder", "ar": "سائل لزج بلون كهرماني فاتح، معزز للرغوة ومثبت للقوام واللزوجة" },
    "packaging": { "en": "200 Kg drums", "ar": "براميل 200 كجم" },
    "applications": { "en": ["Liquid detergents viscosity enhancement", "Hand washes & bubble baths", "Foam stabilization"], "ar": ["رفع اللزوجة في المنظفات السائلة", "صابون غسيل الأيدي والشامبوهات", "تثبيت الرغوة ومنع تلاشيها"] },
    "imageUrl": "/images/catalog/cdea-comperlan.svg",
    "featured": False
  },
  {
    "id": "capb-betaine",
    "name": { "en": "Cocamidopropyl Betaine (CAPB / Betaine 99%)", "ar": "بيتاين كوكاميدو بروبيل (CAPB / Betaine 99%)" },
    "category": "detergent-raw-materials",
    "casNumber": "61789-40-0",
    "formula": "Amphoteric Surfactant",
    "appearance": { "en": "Clear light yellow liquid / 99% pure powder", "ar": "سائل رائق مائل للصفرة / بودرة نقية 99%، مادة سطحية معتدلة ولطيفة على البشرة" },
    "packaging": { "en": "200 Kg drums / 1000L IBC / 25 Kg bags", "ar": "براميل 200 كجم / حاويات IBC / أكياس 25 كجم" },
    "applications": { "en": ["Mild baby shampoos and body washes", "Secondary foaming agent in liquid detergents", "Antistatic agent"], "ar": ["شامبوهات الأطفال والمنتجات الحساسة", "معزز رغوة ثانوي في سوائل التنظيف", "مضاد للكهرباء الساكنة"] },
    "imageUrl": "/images/catalog/capb-betaine.svg",
    "featured": False
  },
  {
    "id": "polysorbate",
    "name": { "en": "Polysorbate (Tween Series)", "ar": "بولي سوربات (Tween)" },
    "category": "detergent-raw-materials",
    "casNumber": "9005-64-5",
    "formula": "Polyoxyethylene Sorbitan Ester",
    "appearance": { "en": "Oily amber liquid non-ionic emulsifier", "ar": "سائل زيتي كهرماني، مستحلب ومذيب غير أيوني للعطور والزيوت الأساسية" },
    "packaging": { "en": "200 Kg drums / 25 Kg cans", "ar": "براميل 200 كجم / جوالين 25 كجم" },
    "applications": { "en": ["Solubilizer for fragrance oils in detergents", "Cosmetic lotions and creams", "Industrial emulsion formulations"], "ar": ["إذابة الزيوت العطرية في المنظفات والماء", "مستحضرات التجميل والكريمات", "المستحلبات الصناعية"] },
    "imageUrl": "/images/catalog/polysorbate.svg",
    "featured": False
  },
  {
    "id": "citric-acid",
    "name": { "en": "Citric Acid (Anhydrous & Monohydrate)", "ar": "حمض الستريك (ملح الليمون)" },
    "category": "detergent-raw-materials",
    "casNumber": "77-92-9",
    "formula": "C6H8O7",
    "appearance": { "en": "White crystalline odorless powder", "ar": "بلورات وبودرة بيضاء عديمة الرائحة" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس 25 كجم" },
    "applications": { "en": ["pH adjuster and descaler in detergents", "Water softening and chelating agent", "Industrial cleaners"], "ar": ["ضبط درجة الحموضة pH وإزالة التكلسات", "تيسير الماء وربط أيونات الكالسيوم", "منظفات الغسالات ومكائن التبريد"] },
    "imageUrl": "/images/catalog/citric-acid.svg",
    "featured": False
  },
  {
    "id": "dcmx",
    "name": { "en": "DCMX (Dichlorometaxylenol)", "ar": "ثنائي كلورو ميتا زيلينول (DCMX - مطهّر ومعقم)" },
    "category": "detergent-raw-materials",
    "casNumber": "133-53-9",
    "formula": "C8H8Cl2O",
    "appearance": { "en": "Off-white crystalline powder with high bactericidal power", "ar": "بودرة بلورية بيضاء مائلة للبيج ذات قدرة تعقيم فائقة ضد البكتيريا والفطريات" },
    "packaging": { "en": "25 Kg drums / bags", "ar": "براميل وأكياس 25 كجم" },
    "applications": { "en": ["Antiseptic liquids and disinfectant soaps", "Hospital and household sanitizers", "Personal hygiene formulations"], "ar": ["المطهرات وسوائل التعقيم المعتمدة", "صابون النظافة الصحية والمستشفيات", "معقمات الأرضيات والأسطح"] },
    "imageUrl": "/images/catalog/dcmx.svg",
    "featured": False
  },
  {
    "id": "shmp",
    "name": { "en": "Sodium Hexametaphosphate (SHMP 68%)", "ar": "سداسي ميتا فوسفات الصوديوم (SHMP)" },
    "category": "detergent-raw-materials",
    "casNumber": "10124-56-8",
    "formula": "(NaPO3)6",
    "appearance": { "en": "White powder/flakes, modified by carbon and oxide purification", "ar": "بودرة / رقائق بيضاء نقية معالجة بالكربون والأكاسيد" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية 25 كجم" },
    "applications": { "en": ["Water treatment in paints (complexes salts to improve properties)", "Detergent builder and water softener", "Boiler water conditioning"], "ar": ["معالجة مياه خلط الدهانات لمنع ترسب الأملاح", "معزز وميسر ماء في صناعة المنظفات", "معالجة مياه المراجل والغلايات"] },
    "imageUrl": "/images/catalog/shmp.svg",
    "featured": True
  },
  {
    "id": "smbs",
    "name": { "en": "Sodium Metabisulfite (SMBS 97%)", "ar": "ميتابيسلفيت الصوديوم (SMBS)" },
    "category": "detergent-raw-materials",
    "casNumber": "7681-57-4",
    "formula": "Na2S2O5",
    "appearance": { "en": "White crystalline powder with bleaching & antioxidant properties", "ar": "بودرة بلورية بيضاء ذات خواص قصر وتبييض ومقاومة قوية للأكسدة" },
    "packaging": { "en": "25 Kg multi-layer paper bags", "ar": "أكياس ورقية 25 كجم" },
    "applications": { "en": ["Bleach to lighten colors in industrial formulations", "Antioxidant to prevent product discoloration or damage", "Water treatment dechlorination"], "ar": ["مادة قاصرة ومبيضة لتفتيح ألوان المنتجات", "مضاد أكسدة لحماية المنتجات من تغير اللون والتلف", "معالجة المياه وإزالة الكلور"] },
    "imageUrl": "/images/catalog/smbs.svg",
    "featured": True
  },
  {
    "id": "detergent-perfume-colors",
    "name": { "en": "Industrial Detergent Perfumes & Colors", "ar": "معطرات وملونات المنظفات الصناعية" },
    "category": "detergent-raw-materials",
    "casNumber": "Various-Mix",
    "formula": "Concentrated Essences & Dyes",
    "appearance": { "en": "High-stability fragrances & water-soluble dyes", "ar": "عطور زيتية ومركزة وثابتة، وألوان سائلة وبودرة قابلة للذوبان" },
    "packaging": { "en": "25 Kg cans / 5 Kg containers", "ar": "جوالين 25 كجم / عبوات 5 كجم" },
    "applications": { "en": ["Dishwashing and floor cleaners aromatization", "Fabric softeners scenting", "Liquid soap coloring"], "ar": ["تعطير وتلوين صابون الصحون ومنظف الأرضيات", "منعمات الأقمشة", "الصابون السائل والشامبوهات"] },
    "imageUrl": "/images/catalog/detergent-perfume-colors.svg",
    "featured": False
  },

  # 6. Special Oils & Waxes (7 items)
  {
    "id": "dblo-linseed-oil",
    "name": { "en": "Double Boiled Linseed Oil (DBLO)", "ar": "زيت بذر الكتان المغلي المزدوج (DBLO)" },
    "category": "special-oils-waxes",
    "casNumber": "68553-15-1",
    "formula": "Oxidized Linseed Oil",
    "appearance": { "en": "Viscous amber golden natural drying oil", "ar": "زيت تجفيف طبيعي كهرماني ذهبي لزج سريع الجفاف" },
    "packaging": { "en": "200 Kg steel drums / 18L tins", "ar": "براميل 200 كجم / صفائح 18 لتر" },
    "applications": { "en": ["Traditional wood finishes and teak treatments", "Oil-based varnishes & artist paints", "Concrete sealing"], "ar": ["حماية وتشطيب الأخشاب والتيك الطبيعي", "الورنيشات الزيتية وألوان الرسم", "عزل المسام الخرسانية"] },
    "imageUrl": "/images/catalog/dblo-linseed-oil.svg",
    "featured": False
  },
  {
    "id": "pine-oil",
    "name": { "en": "Pine Oil 85%", "ar": "زيت الصنوبر المطهر 85%" },
    "category": "special-oils-waxes",
    "casNumber": "8002-09-3",
    "formula": "Terpene Alcohols Blend",
    "appearance": { "en": "Clear light straw liquid with refreshing pine scent", "ar": "سائل رائق بلون قشي فاتح برائحة صنوبر طبيعية ومطهرة" },
    "packaging": { "en": "190 Kg drums / 20 Kg cans", "ar": "براميل 190 كجم / جوالين 20 كجم" },
    "applications": { "en": ["Floor cleaners & pine disinfectants", "Industrial degreasers", "Mineral flotation frother"], "ar": ["منظفات ومطهرات الأرضيات برائحة الصنوبر", "مزيلات الزيوت والشحوم الصناعية", "تعويم المعادن"] },
    "imageUrl": "/images/catalog/pine-oil.svg",
    "featured": False
  },
  {
    "id": "castor-oil",
    "name": { "en": "Castor Oil (First Special Grade)", "ar": "زيت الخروع الصناعي النقي" },
    "category": "special-oils-waxes",
    "casNumber": "8001-79-4",
    "formula": "Ricinoleic Acid Triglyceride",
    "appearance": { "en": "Viscous pale yellow natural oil", "ar": "زيت نباتي طبيعي لزج بلون أصفر شاحب" },
    "packaging": { "en": "200 Kg drums", "ar": "براميل 200 كجم" },
    "applications": { "en": ["Polyurethane polyols raw material", "Lubricants and brake fluids", "Cosmetics and alkyd resins"], "ar": ["المادة الخام لبوليولات البولي يوريثان", "زيوت التزييت وسوائل الفرامل", "مستحضرات التجميل وراتنجات الألكيد"] },
    "imageUrl": "/images/catalog/castor-oil.svg",
    "featured": False
  },
  {
    "id": "glycerin",
    "name": { "en": "Glycerin (Pure Glycerol USP 99.5%)", "ar": "الجلسرين النقي (Glycerin 99.5% USP)" },
    "category": "special-oils-waxes",
    "casNumber": "56-81-5",
    "formula": "C3H8O3",
    "appearance": { "en": "Colorless transparent clear thick viscous liquid", "ar": "سائل شفاف رائق عديم اللون شديد اللزوجة حلو المذاق" },
    "packaging": { "en": "250 Kg drums / IBC", "ar": "براميل 250 كجم / حاويات IBC" },
    "applications": { "en": ["Humectant and moisturizer in personal care & detergents", "Alkyd resins synthesis", "Lubricant and plasticizer"], "ar": ["مرطب وملدّن في المنظفات ومستحضرات العناية", "تصنيع الراتنجات الألكيدية والدهانات", "المواد الصيدلانية وموانع التجمد"] },
    "imageUrl": "/images/catalog/glycerin.svg",
    "featured": True
  },
  {
    "id": "white-petroleum-jelly",
    "name": { "en": "White Petroleum Jelly (Vaseline)", "ar": "الفازلين الأبيض النقي (White Petroleum Jelly)" },
    "category": "special-oils-waxes",
    "casNumber": "8009-03-8",
    "formula": "Hydrocarbon Semi-Solid",
    "appearance": { "en": "Pure white translucent odorless ointment paste", "ar": "معجون هلامي أبيض ناصع نقي عديم الرائحة" },
    "packaging": { "en": "175 Kg steel drums / 50 Kg drums", "ar": "براميل حديدية 175 كجم / 50 كجم" },
    "applications": { "en": ["Cosmetics & skin creams", "Rust preventative barrier coating", "Leather softeners & electrical insulation grease"], "ar": ["مستحضرات العناية بالبشرة والكريمات", "طبقة عازلة واقية من الصدأ للمعادن", "تليين الجلود وعزل التوصيلات الكهربائية"] },
    "imageUrl": "/images/catalog/white-petroleum-jelly.svg",
    "featured": False
  },
  {
    "id": "liquid-paraffin",
    "name": { "en": "Liquid Paraffin (White Mineral Oil)", "ar": "البارافين السائل (الزيت الأبيض المعدني)" },
    "category": "special-oils-waxes",
    "casNumber": "8042-47-5",
    "formula": "Refined Liquid Hydrocarbons",
    "appearance": { "en": "Crystal clear colorless odorless mobile oil", "ar": "زيت معدني نقي كريستالي عديم اللون والرائحة تماماً" },
    "packaging": { "en": "170 Kg drums / IBC", "ar": "براميل 170 كجم / حاويات IBC" },
    "applications": { "en": ["Cosmetics and baby oils", "Polishes for furniture and cars", "Textile machinery lubrication"], "ar": ["مستحضرات التجميل وزيوت الأطفال", "ملمعات الأثاث والسيارات", "تزييت ماكينات النسيج والغزل"] },
    "imageUrl": "/images/catalog/liquid-paraffin.svg",
    "featured": False
  },
  {
    "id": "paraffin-wax",
    "name": { "en": "Paraffin Wax (Fully Refined)", "ar": "شمع البارافين (كامل النقاء)" },
    "category": "special-oils-waxes",
    "casNumber": "8002-74-2",
    "formula": "CnH2n+2",
    "appearance": { "en": "Pure white solid slabs / pastilles, melt point 58-60C", "ar": "ألواح وحبيبات صلبة بيضاء نقية بدرجة انصهار 58-60 مئوية" },
    "packaging": { "en": "25 Kg carton boxes", "ar": "كراتين 25 كجم" },
    "applications": { "en": ["Candle manufacturing", "Waterproofing for packaging & wood boards", "Rubber anti-ozonant", "Match industry"], "ar": ["صناعة الشموع الفاخرة", "عزل الرطوبة في الكرتون والأخشاب", "حماية المطاط من الأوزون والتشقق", "صناعة الثقاب"] },
    "imageUrl": "/images/catalog/paraffin-wax.svg",
    "featured": False
  }
]

with open('src/data/customProducts.json', 'w', encoding='utf-8') as f:
    json.dump(products, f, indent=2, ensure_ascii=False)

print(f"Written {len(products)} products to src/data/customProducts.json")
